name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --manifest-path=2019/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path=2019/Cargo.toml --verbose
